---

- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "main.yml"

- name: Update apt cache (on Debian).
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install required packages for Fetchmail
  package:
    name: "{{ fetchmail_packages }}"
    state: present
  tags:
    - packages

- name: Ensure Fetchmail can start
  ansible.builtin.lineinfile:
    path: /etc/default/fetchmail
    regexp: '^START_DAEMON='
    line: 'START_DAEMON=yes'
  when: fetchmail_service_enabled

- name: Ensure Fetchmail can not start
  ansible.builtin.lineinfile:
    path: /etc/default/fetchmail
    regexp: '^START_DAEMON='
    line: 'START_DAEMON=no'
  when: not fetchmail_service_enabled

- name: Copy Fetchmail configuration
  copy:
    content: "{{ fetchmail_config | default('# No config') }}"
    dest: "{{ fetchmail_config_dir | default('/etc') }}/fetchmailrc"
    owner: "{{ fetchmail_config_owner | default('root') }}"
    group: "{{ fetchmail_config_group | default('root') }}"
    mode: "{{ fetchmail_config_mode | default('0600') }}"
  notify: restart fetchmail

- name: Configure Fetchmail service
  service:
    name: "{{ fetchmail_service_name }}"
    state: "{{ fetchmail_service_state }}"
    enabled: "{{ fetchmail_service_enabled }}"
  tags:
    - configuration
    - policy
